/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/app/': RouteRecordInfo<'/app/', '/app', Record<never, never>, Record<never, never>>,
    '/app/my-data': RouteRecordInfo<'/app/my-data', '/app/my-data', Record<never, never>, Record<never, never>>,
    '/community/': RouteRecordInfo<'/community/', '/community', Record<never, never>, Record<never, never>>,
    '/community/new': RouteRecordInfo<'/community/new', '/community/new', Record<never, never>, Record<never, never>>,
    '/explore': RouteRecordInfo<'/explore', '/explore', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/protocols/': RouteRecordInfo<'/protocols/', '/protocols', Record<never, never>, Record<never, never>>,
    '/unstudies/[id]/': RouteRecordInfo<'/unstudies/[id]/', '/unstudies/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/unstudies/[id]/join': RouteRecordInfo<'/unstudies/[id]/join', '/unstudies/:id/join', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/unstudies/new': RouteRecordInfo<'/unstudies/new', '/unstudies/new', Record<never, never>, Record<never, never>>,
  }
}
