version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app
      - frontend:/app/frontend/
    env_file: 
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    command: sh /app/scripts/start_celery.sh


volumes:
  postgres_data:
  frontend:
